import { Venue } from "./types";

export const vibeCards = [
  { id: "social", emoji: "🥂", title: "Socialt" },
  { id: "cocktails", emoji: "🍸", title: "Cocktails" },
  { id: "party", emoji: "🪩", title: "Drag" },
  { id: "beer", emoji: "🍺", title: "Pub/öl" },
  { id: "date", emoji: "✨", title: "Date" },
  { id: "casual", emoji: "🙂", title: "Casual" }
] as const;

export const venues: Venue[] = [
  {
    id: "boca",
    name: "Boca",
    type: "Cocktailbar",
    area: "Centrum",
    city: "vasteras",
    lat: 59.6118,
    lng: 16.5467,
    price: 3,
    energy: 74,
    crowd: 68,
    age: 20,
    beer: 72,
    drink: 138,
    interior: "Mörk lounge",
    fit: ["cocktails", "date", "social"],
    note: "Snygg start eller mittstopp.",
    review: "Cocktailbar/loungeläge med bra service enligt många omdömen.",
    imageUrl: "https://www.bocavasteras.se/",
    reviewUrl: "https://www.tripadvisor.se/Restaurant_Review-g189878-d1054458-Reviews-Boca-Vasteras_Vastmanland_County.html"
  },
  {
    id: "barlokal",
    name: "Bar Lokal",
    type: "Bar / AW",
    area: "Centrum",
    city: "vasteras",
    lat: 59.6108,
    lng: 16.5444,
    price: 2,
    energy: 66,
    crowd: 61,
    age: 18,
    beer: 59,
    drink: 122,
    interior: "Urban och avslappnad",
    fit: ["social", "casual"],
    note: "Lätt att börja på.",
    review: "Låg tröskel och social citykänsla.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Bar+Lokal+V%C3%A4ster%C3%A5s",
    reviewUrl: "https://www.google.com/search?q=Bar+Lokal+V%C3%A4ster%C3%A5s+reviews"
  },
  {
    id: "bishops-vasteras",
    name: "The Bishops Arms",
    type: "Pub",
    area: "Centrum",
    city: "vasteras",
    lat: 59.6117,
    lng: 16.5448,
    price: 2,
    energy: 56,
    crowd: 54,
    age: 18,
    beer: 56,
    drink: 118,
    interior: "Klassisk brittisk pub",
    fit: ["beer", "casual"],
    note: "Tryggt ölstopp.",
    review: "Pubmiljö och samtalsvänlig vibe.",
    imageUrl: "https://www.bishopsarms.com/vara-pubar/vasteras/",
    reviewUrl: "https://www.tripadvisor.com/Restaurant_Review-g189878-d1054387-Reviews-The_Bishops_Arms-Vasteras_Vastmanland_County.html"
  },
  {
    id: "skybar-vasteras",
    name: "Sky Bar",
    type: "Hotellbar",
    area: "Centrum",
    city: "vasteras",
    lat: 59.6094,
    lng: 16.5433,
    price: 4,
    energy: 63,
    crowd: 57,
    age: 20,
    beer: 74,
    drink: 145,
    interior: "Elegant med utsikt",
    fit: ["date", "cocktails"],
    note: "Bra date- och premiumstart.",
    review: "Utsikt och hotellbarkänsla.",
    imageUrl: "https://plazavasteras.se/skybar/",
    reviewUrl: "https://www.tripadvisor.se/Restaurant_Review-g189878-d1043527-Reviews-Sky_Bar-Vasteras_Vastmanland_County.html"
  },
  {
    id: "steam",
    name: "Steam Hotel Bar",
    type: "Destinationbar",
    area: "Kokpunkten",
    city: "vasteras",
    lat: 59.6038,
    lng: 16.5658,
    price: 4,
    energy: 69,
    crowd: 60,
    age: 20,
    beer: 78,
    drink: 149,
    interior: "Industriell premium",
    fit: ["date", "cocktails", "party"],
    note: "Mer upplevelse än cityloop.",
    review: "Bra wow-känsla och hotellmiljö.",
    imageUrl: "https://www.steamhotel.se/restauranger/barer/",
    reviewUrl: "https://www.google.com/search?q=Steam+Hotel+bar+V%C3%A4ster%C3%A5s+reviews"
  },
  {
    id: "kaj9",
    name: "Kajplats 9",
    type: "Restaurangbar",
    area: "Hamnen",
    city: "vasteras",
    lat: 59.6086,
    lng: 16.5508,
    price: 3,
    energy: 61,
    crowd: 56,
    age: 18,
    beer: 66,
    drink: 126,
    interior: "Ljus och social",
    fit: ["social", "casual"],
    note: "Avslappnat och snyggt.",
    review: "Bra restaurangbar med social känsla.",
    imageUrl: "https://kajplats9.se/",
    reviewUrl: "https://www.google.com/search?q=Kajplats+9+V%C3%A4ster%C3%A5s+reviews"
  },
  {
    id: "hattfabriken",
    name: "Hattfabriken",
    type: "Nattklubb",
    area: "Centrum",
    city: "vasteras",
    lat: 59.6109,
    lng: 16.5457,
    price: 3,
    energy: 89,
    crowd: 81,
    age: 20,
    beer: 69,
    drink: 139,
    interior: "Klubbigare med ljus och sent fokus",
    fit: ["party", "social"],
    note: "För rundor som ska sluta i utgång.",
    review: "Starkt sista stopp för nattliv.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Hattfabriken+V%C3%A4ster%C3%A5s",
    reviewUrl: "https://www.google.com/search?q=Hattfabriken+V%C3%A4ster%C3%A5s+reviews"
  },

  {
    id: "tjoget",
    name: "Tjoget",
    type: "Cocktailbar / kvarterskrog",
    area: "Hornstull",
    city: "stockholm",
    lat: 59.3157,
    lng: 18.0339,
    price: 3,
    energy: 77,
    crowd: 70,
    age: 20,
    beer: 76,
    drink: 158,
    interior: "Stimmig, varm och social",
    fit: ["cocktails", "social", "casual"],
    note: "Bra social cocktailrunda.",
    review: "Prisad bar med avslappnad men kvalitativ vibe.",
    imageUrl: "https://www.tjoget.com/",
    reviewUrl: "https://www.tripadvisor.se/Restaurant_Review-g189852-d21283892-Reviews-Tjoget-Stockholm.html"
  },
  {
    id: "gemma",
    name: "A Bar Called Gemma",
    type: "Cocktailbar",
    area: "Östermalm",
    city: "stockholm",
    lat: 59.3385,
    lng: 18.0781,
    price: 4,
    energy: 73,
    crowd: 62,
    age: 20,
    beer: 82,
    drink: 168,
    interior: "Dimmad, intim och kreativ",
    fit: ["cocktails", "date"],
    note: "Premium cocktailvibe med tydlig identitet.",
    review: "Bra för snygg, samtida drinkkväll snarare än ren klubbpuls.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=A+Bar+Called+Gemma+Stockholm",
    reviewUrl: "https://www.google.com/search?q=A+Bar+Called+Gemma+Stockholm+reviews"
  },
  {
    id: "lucys",
    name: "Lucy's Flower Shop",
    type: "Cocktailbar",
    area: "Östermalm",
    city: "stockholm",
    lat: 59.3388,
    lng: 18.0785,
    price: 4,
    energy: 72,
    crowd: 64,
    age: 20,
    beer: 82,
    drink: 170,
    interior: "Mörk speakeasy-känsla med lila ljus",
    fit: ["cocktails", "date", "social"],
    note: "Bra för mer wow-ig cocktailstart.",
    review: "Hidden-door-känsla och väldigt tydlig baridentitet.",
    imageUrl: "https://www.lucysstockholm.se/",
    reviewUrl: "https://www.google.com/search?q=Lucys+Flower+Shop+Stockholm+reviews"
  },
  {
    id: "coquetel",
    name: "Coquetel Social",
    type: "Cocktailbar",
    area: "Östermalm",
    city: "stockholm",
    lat: 59.3382,
    lng: 18.0773,
    price: 4,
    energy: 71,
    crowd: 60,
    age: 20,
    beer: 84,
    drink: 170,
    interior: "Elegant casual cocktailbar",
    fit: ["cocktails", "date", "social"],
    note: "Snygg men inte stel känsla.",
    review: "Bra när användaren vill ha uppstyrt men fortfarande socialt.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Coquetel+Social+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Coquetel+Social+Stockholm+reviews"
  },
  {
    id: "rodahuset",
    name: "Röda Huset",
    type: "Cocktailbar",
    area: "Norrmalm",
    city: "stockholm",
    lat: 59.3322,
    lng: 18.0606,
    price: 4,
    energy: 74,
    crowd: 66,
    age: 20,
    beer: 84,
    drink: 172,
    interior: "Modern, nordisk och designad",
    fit: ["cocktails", "date", "social"],
    note: "Tydligt premium men fortfarande levande.",
    review: "Bra toppbar när kvällen ska kännas modern och genomtänkt.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=R%C3%B6da+Huset+Stockholm",
    reviewUrl: "https://www.google.com/search?q=R%C3%B6da+Huset+Stockholm+reviews"
  },
  {
    id: "pharmarium",
    name: "Pharmarium",
    type: "Cocktailbar",
    area: "Gamla stan",
    city: "stockholm",
    lat: 59.3249,
    lng: 18.0717,
    price: 4,
    energy: 72,
    crowd: 64,
    age: 20,
    beer: 84,
    drink: 172,
    interior: "Historisk, mörk och dramatisk cocktailmiljö",
    fit: ["cocktails", "date", "social"],
    note: "Mer destination-lik cocktailkänsla.",
    review: "Bra när rundan ska kännas speciell redan från första glaset.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Pharmarium+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Pharmarium+Stockholm+reviews"
  },
  {
    id: "herno",
    name: "Hernö Gin Bar",
    type: "Ginbar",
    area: "Gamla stan",
    city: "stockholm",
    lat: 59.3244,
    lng: 18.0729,
    price: 4,
    energy: 60,
    crowd: 52,
    age: 20,
    beer: 82,
    drink: 166,
    interior: "Smal, nischad och spiritfokuserad",
    fit: ["cocktails", "date", "casual"],
    note: "Bra nischstopp för gin- och drinkintresserade.",
    review: "Passar kvällar som ska kännas mer kunniga än stökiga.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Hern%C3%B6+Gin+Bar+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Hern%C3%B6+Gin+Bar+Stockholm+reviews"
  },
  {
    id: "surfers",
    name: "Surfers Bar",
    type: "Cocktailbar / restaurangbar",
    area: "Norrmalm",
    city: "stockholm",
    lat: 59.3334,
    lng: 18.0562,
    price: 3,
    energy: 71,
    crowd: 63,
    age: 20,
    beer: 78,
    drink: 158,
    interior: "Livlig, exotisk och färgstark",
    fit: ["cocktails", "social", "party"],
    note: "Bra när du vill ha energi men inte ren klubb ännu.",
    review: "Bra mellanstopp där maten och barenergin möts på rätt sätt.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Surfers+Stockholm+bar",
    reviewUrl: "https://www.google.com/search?q=Surfers+Stockholm+bar+reviews"
  },
  {
    id: "tak",
    name: "TAK / SUS",
    type: "Rooftopbar / restaurangbar",
    area: "Norrmalm",
    city: "stockholm",
    lat: 59.3316,
    lng: 18.0686,
    price: 4,
    energy: 75,
    crowd: 68,
    age: 20,
    beer: 86,
    drink: 172,
    interior: "Rooftop, modern och utsiktsdriven",
    fit: ["date", "cocktails", "social"],
    note: "Bra premiumrunda med utsikt och kvällskänsla.",
    review: "Passar när kvällen ska kännas stor redan tidigt.",
    imageUrl: "https://tak.se/",
    reviewUrl: "https://www.google.com/search?q=TAK+Stockholm+reviews"
  },
  {
    id: "berns",
    name: "Berns",
    type: "Nattliv / restaurangbar",
    area: "Norrmalm",
    city: "stockholm",
    lat: 59.3325,
    lng: 18.0739,
    price: 4,
    energy: 84,
    crowd: 76,
    age: 20,
    beer: 84,
    drink: 166,
    interior: "Historisk, större och glamorös",
    fit: ["party", "social", "date"],
    note: "Bra övergång från middag/bar till nattliv.",
    review: "Starkt val när kvällen ska kännas mer uppklädd.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Berns+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Berns+Stockholm+reviews"
  },
  {
    id: "riche",
    name: "Riche",
    type: "Restaurangbar",
    area: "Östermalm",
    city: "stockholm",
    lat: 59.3346,
    lng: 18.0751,
    price: 4,
    energy: 78,
    crowd: 72,
    age: 20,
    beer: 82,
    drink: 168,
    interior: "Klassisk storstad, tät och social",
    fit: ["social", "date", "casual"],
    note: "Mer restaurangbar än ren cocktailbar, men kvällsstark.",
    review: "Bra för kvällar där man vill att middag och bar flyter ihop.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Riche+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Riche+Stockholm+reviews"
  },
  {
    id: "sturehof",
    name: "Sturehof",
    type: "Restaurangbar",
    area: "Östermalm",
    city: "stockholm",
    lat: 59.3349,
    lng: 18.0737,
    price: 4,
    energy: 73,
    crowd: 69,
    age: 20,
    beer: 88,
    drink: 174,
    interior: "Klassisk, tät och välklädd",
    fit: ["social", "date"],
    note: "Bra för den som vill ha mer klassisk Stockholmskväll.",
    review: "Fungerar när restaurangkänslan ska glida över i kvällsbar.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Sturehof+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Sturehof+Stockholm+reviews"
  },
  {
    id: "teatergrillen",
    name: "Teatergrillen",
    type: "Restaurangbar",
    area: "Östermalm",
    city: "stockholm",
    lat: 59.3344,
    lng: 18.0735,
    price: 4,
    energy: 70,
    crowd: 63,
    age: 20,
    beer: 86,
    drink: 168,
    interior: "Mörk, klassisk och kvällsvänlig",
    fit: ["date", "social", "casual"],
    note: "Bra för vuxnare kväll med restaurangbar-ton.",
    review: "Passar bra när man vill hålla kvällen elegant men inte stel.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Teatergrillen+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Teatergrillen+Stockholm+reviews"
  },
  {
    id: "omaka",
    name: "Omaka",
    type: "Brewpub",
    area: "Östermalm",
    city: "stockholm",
    lat: 59.3434,
    lng: 18.0803,
    price: 3,
    energy: 62,
    crowd: 55,
    age: 18,
    beer: 74,
    drink: 148,
    interior: "Bryggerikänsla, öl i fokus",
    fit: ["beer", "social", "casual"],
    note: "Bra pub/öl-spår i Stockholm.",
    review: "Bra laidback stopp för craft beer-kvällar.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Omaka+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Omaka+Stockholm+reviews"
  },
  {
    id: "tweed",
    name: "Tweed",
    type: "Whiskybar / hotellbar",
    area: "Vasastan",
    city: "stockholm",
    lat: 59.3372,
    lng: 18.0546,
    price: 3,
    energy: 55,
    crowd: 49,
    age: 20,
    beer: 78,
    drink: 154,
    interior: "Mörk, vuxen hotellbarkänsla",
    fit: ["beer", "date", "casual"],
    note: "Lugnare och mer vuxet stopp.",
    review: "Bra för stillsam men stark kvällskänsla.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Tweed+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Tweed+Stockholm+reviews"
  },
  {
    id: "pelago",
    name: "Pelago",
    type: "Terrassbar / restaurangbar",
    area: "Södermalm",
    city: "stockholm",
    lat: 59.3169,
    lng: 18.0706,
    price: 4,
    energy: 79,
    crowd: 74,
    age: 20,
    beer: 82,
    drink: 164,
    interior: "Terrass, sommarpuls och öppen miljö",
    fit: ["social", "party", "date"],
    note: "Bra när du vill ha mer öppen kvällsenergi än ren klubb.",
    review: "Passar starkt som övergång mellan social drink och sen kväll.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Pelago+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Pelago+Stockholm+reviews"
  },
  {
    id: "freyja",
    name: "Freyja",
    type: "Rooftop / restaurangbar",
    area: "Södermalm",
    city: "stockholm",
    lat: 59.3129,
    lng: 18.0738,
    price: 4,
    energy: 76,
    crowd: 69,
    age: 20,
    beer: 84,
    drink: 168,
    interior: "Modern nordisk rooftop-känsla",
    fit: ["date", "social", "cocktails"],
    note: "Bra när kvällen ska kännas snygg, stor och ny.",
    review: "Passar för premiumkänsla utan att bli för stel.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Freyja+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Freyja+Stockholm+reviews"
  },
  {
    id: "tradgarden",
    name: "Trädgården",
    type: "Utomhusklubb / bar",
    area: "Skanstull",
    city: "stockholm",
    lat: 59.3052,
    lng: 18.0815,
    price: 3,
    energy: 90,
    crowd: 84,
    age: 21,
    beer: 79,
    drink: 155,
    interior: "Festivalig, färgstark och öppen",
    fit: ["party", "social", "casual"],
    note: "Fritt nattlivsspår.",
    review: "Bra när kvällen ska sluta mer levande än polerad.",
    imageUrl: "https://www.tradgarden.com/",
    reviewUrl: "https://www.google.com/search?q=Tr%C3%A4dg%C3%A5rden+Stockholm+reviews"
  },
  {
    id: "slakthuset",
    name: "Slakthuset",
    type: "Nattklubb",
    area: "Johanneshov",
    city: "stockholm",
    lat: 59.2929,
    lng: 18.0831,
    price: 3,
    energy: 92,
    crowd: 86,
    age: 21,
    beer: 80,
    drink: 158,
    interior: "Industriell klubbmiljö med tung puls",
    fit: ["party", "social"],
    note: "Bra ren klubbfinal när energin ska maxas.",
    review: "Passar när man verkligen vill att kvällen ska sluta i nattliv.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=Slakthuset+Stockholm",
    reviewUrl: "https://www.google.com/search?q=Slakthuset+Stockholm+reviews"
  },
  {
    id: "spybar",
    name: "Spy Bar",
    type: "Nattklubb",
    area: "Stureplan",
    city: "stockholm",
    lat: 59.3348,
    lng: 18.0738,
    price: 4,
    energy: 92,
    crowd: 86,
    age: 23,
    beer: 86,
    drink: 170,
    interior: "Klassisk Stureplansklubb",
    fit: ["party", "social"],
    note: "Ren klubbfinal.",
    review: "Bra när kvällen ska kännas mer ikonisk än avslappnad.",
    imageUrl: "https://www.stureplansgruppen.se/nightlife/spy-bar/",
    reviewUrl: "https://www.google.com/search?q=Spy+Bar+Stockholm+reviews"
  },
  {
    id: "sturecompagniet",
    name: "Sturecompagniet",
    type: "Nattklubb",
    area: "Stureplan",
    city: "stockholm",
    lat: 59.336,
    lng: 18.0736,
    price: 4,
    energy: 91,
    crowd: 85,
    age: 23,
    beer: 84,
    drink: 168,
    interior: "Stor klubb med flera dansgolv",
    fit: ["party", "social"],
    note: "Bra för större klubbfinal.",
    review: "Stark avslutning för användare som vill ha klassisk stor nattklubb.",
    imageUrl: "https://www.stureplansgruppen.se/nightlife/sturecompagniet/",
    reviewUrl: "https://www.google.com/search?q=Sturecompagniet+Stockholm+reviews"
  },
  {
    id: "f12",
    name: "F12 Terrassen",
    type: "Terrass / nattliv",
    area: "Norrmalm",
    city: "stockholm",
    lat: 59.3292,
    lng: 18.0674,
    price: 4,
    energy: 88,
    crowd: 82,
    age: 23,
    beer: 84,
    drink: 170,
    interior: "Öppen terrass, citypuls och nattlivston",
    fit: ["party", "social", "date"],
    note: "Bra som sen cityfinal med mer terrace-klubbkänsla.",
    review: "Passar när kvällen ska sluta centralt och högenergiskt.",
    imageUrl: "https://www.google.com/search?tbm=isch&q=F12+Terrassen+Stockholm",
    reviewUrl: "https://www.google.com/search?q=F12+Terrassen+Stockholm+reviews"
  }
];